language: node_js
sudo: false
node_js:
    - 11
    - 10
    - 9
    - 8
install:
    - npm install

jobs:
    include:
        - stage: build
          script: npm run build
        - stage: unit-test
          script: npm test
