version: '3.5'

services:
  frontend:
    container_name: noodlee-frontend
    image: noodlee-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - noodlee-system-network

networks:
  noodlee-system-network:
    name: noodlee-system-network
    driver: bridge
