export * from './about/about.component';
export * from './contact/contact.component';
export * from './design-section/design-section.component';
export * from './footer/footer.component';
export * from './header/header.component';
export * from './pricing/pricing.component';
export * from './reviews/reviews.component';
export * from './statistics-bar/statistics-bar.component';
export * from './team-section/team-section.component';
